// Generated by CoffeeScript 1.3.3

/*
# ownCloud - News app
#
# @author Bernhard Posselt
# Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
#
# This file is licensed under the Affero General Public License version 3 or later.
# See the COPYING-README file
#
*/


(function() {
  var app, markingRead, scrolling,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('News', []).config(function($provide) {
    var config;
    config = {
      MarkReadTimeout: 500,
      ScrollTimeout: 500,
      initialLoadedItemsNr: 20,
      FeedUpdateInterval: 6000000
    };
    return $provide.value('Config', config);
  });

  app.run([
    'PersistenceNews', function(PersistenceNews) {
      return PersistenceNews.loadInitial();
    }
  ]);

  $(document).ready(function() {
    return $(this).keyup(function(e) {
      if ((e.which === 116) || (e.which === 82 && e.ctrlKey)) {
        document.location.reload(true);
        return false;
      }
    });
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  scrolling = true;

  markingRead = true;

  angular.module('News').directive('whenScrolled', [
    '$rootScope', 'Config', function($rootScope, Config) {
      return function(scope, elm, attr) {
        return elm.bind('scroll', function() {
          if (scrolling) {
            scrolling = false;
            setTimeout(function() {
              return scrolling = true;
            }, Config.ScrollTimeout);
            if (markingRead) {
              markingRead = false;
              setTimeout(function() {
                var $elems, feed, feedItem, id, offset, _i, _len, _results;
                markingRead = true;
                $elems = $(elm).find('.feed_item:not(.read)');
                _results = [];
                for (_i = 0, _len = $elems.length; _i < _len; _i++) {
                  feedItem = $elems[_i];
                  offset = $(feedItem).position().top;
                  if (offset <= -50) {
                    id = parseInt($(feedItem).data('id'), 10);
                    feed = parseInt($(feedItem).data('feed'), 10);
                    _results.push($rootScope.$broadcast('read', {
                      id: id,
                      feed: feed
                    }));
                  } else {
                    break;
                  }
                }
                return _results;
              }, Config.MarkReadTimeout);
            }
            return scope.$apply(attr.whenScrolled);
          }
        });
      };
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').directive('onEnter', function() {
    return function(scope, elm, attr) {
      return elm.bind('keyup', function(e) {
        if (e.keyCode === 13) {
          e.preventDefault();
          return scope.$apply(attr.onEnter);
        }
      });
    };
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').directive('feedNavigation', function() {
    return function(scope, elm, attr) {
      var jumpTo, jumpToNextItem, jumpToPreviousItem;
      jumpTo = function($scrollArea, $item) {
        var position;
        position = $item.offset().top - $scrollArea.offset().top + $scrollArea.scrollTop();
        return $scrollArea.scrollTop(position);
      };
      jumpToPreviousItem = function(scrollArea) {
        var $item, $items, $previous, $scrollArea, item, notJumped, _i, _len;
        $scrollArea = $(scrollArea);
        $items = $scrollArea.find('.feed_item');
        notJumped = true;
        for (_i = 0, _len = $items.length; _i < _len; _i++) {
          item = $items[_i];
          $item = $(item);
          if ($item.position().top >= 0) {
            $previous = $item.prev();
            if ($previous.length > 0) {
              jumpTo($scrollArea, $previous);
            }
            notJumped = false;
            break;
          }
        }
        if ($items.length > 0 && notJumped) {
          return jumpTo($scrollArea, $items.last());
        }
      };
      jumpToNextItem = function(scrollArea) {
        var $item, $items, $scrollArea, item, _i, _len, _results;
        $scrollArea = $(scrollArea);
        $items = $scrollArea.find('.feed_item');
        _results = [];
        for (_i = 0, _len = $items.length; _i < _len; _i++) {
          item = $items[_i];
          $item = $(item);
          if ($item.position().top > 1) {
            jumpTo($scrollArea, $item);
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      return $(document).keydown(function(e) {
        var focused, scrollArea;
        focused = $(':focus');
        if (!(focused.is('input') || focused.is('select') || focused.is('textarea') || focused.is('checkbox') || focused.is('button'))) {
          scrollArea = elm;
          if (e.keyCode === 74 || e.keyCode === 39) {
            return jumpToNextItem(scrollArea);
          } else if (e.keyCode === 75 || e.keyCode === 37) {
            return jumpToPreviousItem(scrollArea);
          }
        }
      });
    };
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  /*
  # This is used to signal the settings bar that the app has been focused and that
  # it should hide
  */


  angular.module('News').directive('appfocus', [
    '$rootScope', function($rootScope) {
      return function(scope, elm, attr) {
        return elm.bind('click', function() {
          $rootScope.$broadcast('appfocus');
          return scope.$apply(attr.appfocus);
        });
      };
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').directive('draggable', function() {
    return function(scope, elm, attr) {
      var details;
      details = {
        revert: true,
        stack: '> li',
        zIndex: 1000,
        axis: 'y'
      };
      return $(elm).draggable(details);
    };
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').directive('droppable', [
    '$rootScope', function($rootScope) {
      return function(scope, elm, attr) {
        var $elem, details;
        $elem = $(elm);
        details = {
          accept: '.feed',
          hoverClass: 'dnd_over',
          greedy: true,
          drop: function(event, ui) {
            var data;
            $('.dnd_over').removeClass('dnd_over');
            data = {
              folderId: parseInt($elem.data('id'), 10),
              feedId: parseInt($(ui.draggable).data('id'), 10)
            };
            $rootScope.$broadcast('moveFeedToFolder', data);
            return scope.$apply(attr.droppable);
          }
        };
        return $elem.droppable(details);
      };
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').filter('feedInFolder', function() {
    return function(feeds, folderId) {
      var feed, result, _i, _len;
      result = [];
      for (_i = 0, _len = feeds.length; _i < _len; _i++) {
        feed = feeds[_i];
        if (feed.folderId === folderId) {
          result.push(feed);
        }
      }
      return result;
    };
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('FeedModel', [
    'Model', '$rootScope', function(Model, $rootScope) {
      var FeedModel;
      FeedModel = (function(_super) {

        __extends(FeedModel, _super);

        function FeedModel($rootScope) {
          FeedModel.__super__.constructor.call(this, 'feeds', $rootScope);
        }

        FeedModel.prototype.add = function(item) {
          return FeedModel.__super__.add.call(this, this.bindAdditional(item));
        };

        FeedModel.prototype.bindAdditional = function(item) {
          if (item.icon === "url()") {
            item.icon = 'url(' + OC.imagePath('news', 'rss.svg') + ')';
          }
          return item;
        };

        return FeedModel;

      })(Model);
      return new FeedModel($rootScope);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('GarbageRegistry', [
    'ItemModel', function(ItemModel) {
      var garbageRegistry;
      garbageRegistry = (function() {

        function garbageRegistry(itemModel) {
          this.itemModel = itemModel;
          this.registeredItemIds = {};
        }

        garbageRegistry.prototype.register = function(item) {
          var itemId;
          itemId = item.id;
          return this.registeredItemIds[itemId] = item;
        };

        garbageRegistry.prototype.unregister = function(item) {
          var itemId;
          itemId = item.id;
          return delete this.registeredItemIds[itemId];
        };

        garbageRegistry.prototype.clear = function() {
          var id, item, _ref;
          _ref = this.registeredItemIds;
          for (id in _ref) {
            item = _ref[id];
            if (!item.isImportant && !item.keptUnread) {
              this.itemModel.removeById(parseInt(id, 10));
            }
            item.keptUnread = false;
          }
          return this.registeredItemIds = {};
        };

        return garbageRegistry;

      })();
      return new garbageRegistry(ItemModel);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('ShowAll', [
    '$rootScope', function($rootScope) {
      var showAll;
      showAll = {
        showAll: false
      };
      showAll.handle = function(data) {
        if (data['showAll'] !== void 0) {
          return showAll.showAll = data['showAll'];
        }
      };
      return showAll;
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('PersistenceNews', [
    'Persistence', '$http', '$rootScope', 'Loading', 'FeedModel', 'FolderModel', 'ItemModel', 'ShowAll', 'StarredCount', 'ActiveFeed', function(Persistence, $http, $rootScope, Loading, FeedModel, FolderModel, ItemModel, ShowAll, StarredCount, ActiveFeed) {
      var PersistenceNews;
      PersistenceNews = (function(_super) {

        __extends(PersistenceNews, _super);

        function PersistenceNews($http, $rootScope, loading, feedModel, folderModel, itemModel, showAll, starredCount, activeFeed) {
          this.$rootScope = $rootScope;
          this.loading = loading;
          PersistenceNews.__super__.constructor.call(this, 'news', $http);
          this.models = [feedModel, folderModel, itemModel, showAll, starredCount, activeFeed];
        }

        PersistenceNews.prototype.updateModels = function(data) {
          var model, _i, _len, _ref, _results;
          _ref = this.models;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            model = _ref[_i];
            _results.push(model.handle(data));
          }
          return _results;
        };

        PersistenceNews.prototype.loadInitial = function() {
          var _this = this;
          this.loading.loading += 1;
          return OC.Router.registerLoadedCallback(function() {
            return _this.post('init', {}, function(json) {
              _this.loading.loading -= 1;
              _this.updateModels(json.data);
              _this.$rootScope.$broadcast('triggerHideRead');
              return _this.setInitialized(true);
            }, null, true);
          });
        };

        PersistenceNews.prototype.loadFeed = function(type, id, latestFeedId, latestTimestamp, limit) {
          var data,
            _this = this;
          if (limit == null) {
            limit = 20;
          }
          data = {
            type: type,
            id: id,
            latestFeedId: latestFeedId,
            latestTimestamp: latestTimestamp,
            limit: limit
          };
          this.loading.loading += 1;
          return this.post('loadfeed', data, function(json) {
            _this.loading.loading -= 1;
            return _this.updateModels(json.data);
          });
        };

        PersistenceNews.prototype.createFeed = function(feedUrl, folderId, onSuccess, onError) {
          var data,
            _this = this;
          data = {
            feedUrl: feedUrl,
            folderId: folderId
          };
          return this.post('createfeed', data, function(json) {
            onSuccess();
            return _this.updateModels(json.data);
          }, onError);
        };

        PersistenceNews.prototype.deleteFeed = function(feedId, onSuccess) {
          var data;
          data = {
            feedId: feedId
          };
          return this.post('deletefeed', data, onSuccess);
        };

        PersistenceNews.prototype.moveFeedToFolder = function(feedId, folderId) {
          var data;
          data = {
            feedId: feedId,
            folderId: folderId
          };
          return this.post('movefeedtofolder', data);
        };

        PersistenceNews.prototype.createFolder = function(folderName, onSuccess) {
          var data,
            _this = this;
          data = {
            folderName: folderName
          };
          return this.post('createfolder', data, function(json) {
            onSuccess();
            return _this.updateModels(json.data);
          });
        };

        PersistenceNews.prototype.deleteFolder = function(folderId) {
          var data;
          data = {
            folderId: folderId
          };
          return this.post('deletefolder', data);
        };

        PersistenceNews.prototype.changeFolderName = function(folderId, newFolderName) {
          var data;
          data = {
            folderId: folderId,
            newFolderName: newFolderName
          };
          return this.post('folderName', data);
        };

        PersistenceNews.prototype.showAll = function(isShowAll) {
          var data;
          data = {
            showAll: isShowAll
          };
          return this.post('setshowall', data);
        };

        PersistenceNews.prototype.markRead = function(itemId, isRead) {
          var data, status;
          if (isRead) {
            status = 'read';
          } else {
            status = 'unread';
          }
          data = {
            itemId: itemId,
            status: status
          };
          return this.post('setitemstatus', data);
        };

        PersistenceNews.prototype.setImportant = function(itemId, isImportant) {
          var data, status;
          if (isImportant) {
            status = 'important';
          } else {
            status = 'unimportant';
          }
          data = {
            itemId: itemId,
            status: status
          };
          return this.post('setitemstatus', data);
        };

        PersistenceNews.prototype.collapseFolder = function(folderId, value) {
          var data;
          data = {
            folderId: folderId,
            opened: value
          };
          return this.post('collapsefolder', data);
        };

        PersistenceNews.prototype.updateFeed = function(feedId) {
          var data,
            _this = this;
          data = {
            feedId: feedId
          };
          return this.post('updatefeed', data, function(json) {
            return _this.updateModels(json.data);
          });
        };

        PersistenceNews.prototype.setAllItemsRead = function(feedId, mostRecentItemId) {
          var data;
          data = {
            feedId: feedId,
            mostRecentItemId: mostRecentItemId
          };
          return this.post('setallitemsread', data);
        };

        return PersistenceNews;

      })(Persistence);
      return new PersistenceNews($http, $rootScope, Loading, FeedModel, FolderModel, ItemModel, ShowAll, StarredCount, ActiveFeed);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('Loading', function() {
    var loading;
    return loading = {
      loading: 0
    };
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('FeedType', function() {
    var feedType;
    return feedType = {
      Feed: 0,
      Folder: 1,
      Starred: 2,
      Subscriptions: 3,
      Shared: 4
    };
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('FolderModel', [
    'Model', '$rootScope', function(Model, $rootScope) {
      var FolderModel;
      FolderModel = (function(_super) {

        __extends(FolderModel, _super);

        function FolderModel($rootScope) {
          FolderModel.__super__.constructor.call(this, 'folders', $rootScope);
        }

        return FolderModel;

      })(Model);
      return new FolderModel($rootScope);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('ActiveFeed', [
    '$rootScope', function($rootScope) {
      var activeFeed;
      activeFeed = {
        id: 0,
        type: 3
      };
      activeFeed.handle = function(data) {
        if (data['activeFeed']) {
          activeFeed.id = data['activeFeed'].id;
          return activeFeed.type = data['activeFeed'].type;
        }
      };
      return activeFeed;
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('ItemModel', [
    'Model', '$rootScope', 'Cache', 'FeedType', function(Model, $rootScope, Cache, FeedType) {
      var ItemModel;
      ItemModel = (function(_super) {

        __extends(ItemModel, _super);

        function ItemModel($rootScope, cache, feedType) {
          this.cache = cache;
          this.feedType = feedType;
          ItemModel.__super__.constructor.call(this, 'items', $rootScope);
        }

        ItemModel.prototype.clearCache = function() {
          this.cache.clear();
          return ItemModel.__super__.clearCache.call(this);
        };

        ItemModel.prototype.add = function(item) {
          item = this.bindAdditional(item);
          ItemModel.__super__.add.call(this, item);
          return this.cache.add(this.getItemById(item.id));
        };

        ItemModel.prototype.bindAdditional = function(item) {
          item.getRelativeDate = function() {
            return moment.unix(this.date).fromNow();
          };
          item.getAuthorLine = function() {
            if (this.author !== null && this.author.trim() !== "") {
              return "by " + this.author;
            } else {
              return "";
            }
          };
          return item;
        };

        ItemModel.prototype.removeById = function(itemId) {
          this.cache.remove(this.getItemById(itemId));
          return ItemModel.__super__.removeById.call(this, itemId);
        };

        ItemModel.prototype.getHighestId = function(type, id) {
          return this.cache.getHighestId(type, id);
        };

        ItemModel.prototype.getHighestTimestamp = function(type, id) {
          return this.cache.getHighestTimestamp(type, id);
        };

        ItemModel.prototype.getLowestId = function(type, id) {
          return this.cache.getLowestId(type, id);
        };

        ItemModel.prototype.getLowestTimestamp = function(type, id) {
          return this.cache.getLowestTimestamp(type, id);
        };

        ItemModel.prototype.getFeedsOfFolderId = function(id) {
          return this.cache.getFeedsOfFolderId(id);
        };

        ItemModel.prototype.getItemsByTypeAndId = function(type, id) {
          var feedId, itemId, items, valid, _i, _len, _ref, _ref1;
          switch (type) {
            case this.feedType.Feed:
              items = this.cache.feedCache[id] || {};
              return items;
            case this.feedType.Subscriptions:
              return this.getItems();
            case this.feedType.Folder:
              this.cache.buildFolderCache(id);
              items = {};
              _ref = this.cache.folderCache[id];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                feedId = _ref[_i];
                $.extend(items, this.cache.feedCache[feedId]);
              }
              return items;
            case this.feedType.Starred:
              items = {};
              _ref1 = this.cache.importantCache;
              for (itemId in _ref1) {
                valid = _ref1[itemId];
                items[itemId] = this.getItemById(itemId);
              }
              return items;
          }
        };

        ItemModel.prototype.setImportant = function(itemId, isImportant) {
          this.cache.setImportant(itemId, isImportant);
          return this.getItemById(itemId).isImportant = isImportant;
        };

        return ItemModel;

      })(Model);
      return new ItemModel($rootScope, Cache, FeedType);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('Persistence', function() {
    var Persistence;
    return Persistence = (function() {

      function Persistence(appName, $http) {
        this.appName = appName;
        this.$http = $http;
        this.appInitialized = false;
        this.shelvedRequests = [];
      }

      Persistence.prototype.setInitialized = function(isInitialized) {
        if (isInitialized) {
          this.executePostRequests();
        }
        return this.appInitialized = isInitialized;
      };

      Persistence.prototype.executePostRequests = function() {
        var request, _i, _len, _ref;
        _ref = this.shelvedRequests;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          request = _ref[_i];
          this.post(request.route, request.data, request.callback);
          console.log(request);
        }
        return this.shelvedRequests = [];
      };

      Persistence.prototype.isInitialized = function() {
        return this.appInitialized;
      };

      Persistence.prototype.post = function(route, data, callback, errorCallback, init) {
        var headers, request, url;
        if (data == null) {
          data = {};
        }
        if (init == null) {
          init = false;
        }
        if (this.isInitialized === false && init === false) {
          request = {
            route: route,
            data: data,
            callback: callback
          };
          this.shelvedRequests.push(request);
          return;
        }
        if (!callback) {
          callback = function() {};
        }
        if (!errorCallback) {
          errorCallback = function() {};
        }
        url = OC.Router.generate("news_ajax_" + route);
        data = $.param(data);
        headers = {
          requesttoken: oc_requesttoken,
          'Content-Type': 'application/x-www-form-urlencoded'
        };
        return this.$http.post(url, data, {
          headers: headers
        }).success(function(data, status, headers, config) {
          if (data.status === "error") {
            return errorCallback(data.msg);
          } else {
            return callback(data);
          }
        }).error(function(data, status, headers, config) {
          console.warn('Error occured: ');
          console.warn(status);
          console.warn(headers);
          return console.warn(config);
        });
      };

      return Persistence;

    })();
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('Model', function() {
    var Model;
    return Model = (function() {

      function Model(reactOn, $rootScope) {
        this.reactOn = reactOn;
        this.$rootScope = $rootScope;
        this.clearCache();
      }

      Model.prototype.handle = function(data) {
        var item, _i, _len, _ref, _results;
        if (data[this.reactOn]) {
          _ref = data[this.reactOn];
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            _results.push(this.add(item));
          }
          return _results;
        }
      };

      Model.prototype.clearCache = function() {
        this.items = [];
        this.itemIds = {};
        return this.markAccessed();
      };

      Model.prototype.markAccessed = function() {
        return this.lastAccessed = new Date().getTime();
      };

      Model.prototype.getLastModified = function() {
        return this.lastAccessed;
      };

      Model.prototype.add = function(item) {
        if (this.itemIds[item.id] === void 0) {
          this.items.push(item);
          this.itemIds[item.id] = item;
          return this.markAccessed();
        } else {
          return this.update(item);
        }
      };

      Model.prototype.update = function(item) {
        var key, updatedItem, value;
        updatedItem = this.itemIds[item.id];
        for (key in item) {
          value = item[key];
          if (key !== 'id') {
            updatedItem[key] = value;
          }
        }
        return this.markAccessed();
      };

      Model.prototype.removeById = function(id) {
        var counter, item, removeItemIndex, _i, _len, _ref;
        removeItemIndex = null;
        counter = 0;
        _ref = this.items;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (item.id === id) {
            removeItemIndex = counter;
            break;
          }
          counter += 1;
        }
        if (removeItemIndex !== null) {
          this.items.splice(removeItemIndex, 1);
          delete this.itemIds[id];
        }
        return this.markAccessed();
      };

      Model.prototype.getItemById = function(id) {
        return this.itemIds[id];
      };

      Model.prototype.getItems = function() {
        return this.items;
      };

      return Model;

    })();
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('StarredCount', [
    '$rootScope', function($rootScope) {
      var starredCount;
      starredCount = {
        count: 0
      };
      starredCount.handle = function(data) {
        if (data['starredCount'] !== void 0) {
          return starredCount.count = data['starredCount'];
        }
      };
      return starredCount;
    }
  ]);

  angular.module('News').factory('Cache', [
    'FeedType', 'FeedModel', 'FolderModel', function(FeedType, FeedModel, FolderModel) {
      var Cache;
      Cache = (function() {

        function Cache(feedType, feedModel, folderModel) {
          this.feedType = feedType;
          this.feedModel = feedModel;
          this.folderModel = folderModel;
          this.clear();
        }

        Cache.prototype.clear = function() {
          this.feedCache = {};
          this.folderCache = {};
          this.folderCacheLastModified = 0;
          this.importantCache = {};
          this.highestId = 0;
          this.lowestId = 0;
          this.highestTimestamp = 0;
          this.lowestTimestamp = 0;
          this.highestIds = {};
          this.lowestIds = {};
          this.highestTimestamps = {};
          return this.lowestTimestamps = {};
        };

        Cache.prototype.add = function(item) {
          if (!this.feedCache[item.feedId]) {
            this.feedCache[item.feedId] = {};
          }
          this.feedCache[item.feedId][item.id] = item;
          if (this.highestTimestamp < item.date) {
            this.highestTimestamp = item.date;
          }
          if (this.lowestTimestamp > item.date) {
            this.lowestTimestamp = item.date;
          }
          if (this.highestId < item.id) {
            this.highestId = item.id;
          }
          if (this.lowestId > item.id) {
            this.lowestId = item.id;
          }
          if (item.isImportant) {
            this.importantCache[item.id] = item;
          }
          if (this.highestTimestamps[item.feedId] === void 0 || item.id > this.highestTimestamps[item.feedId]) {
            this.highestTimestamps[item.feedId] = item.date;
          }
          if (this.lowestTimestamps[item.feedId] === void 0 || item.id > this.lowestTimestamps[item.feedId]) {
            this.lowestTimestamps[item.feedId] = item.date;
          }
          if (this.highestIds[item.feedId] === void 0 || item.id > this.highestIds[item.feedId]) {
            this.highestIds[item.feedId] = item.id;
          }
          if (this.lowestIds[item.feedId] === void 0 || item.id > this.lowestIds[item.feedId]) {
            return this.lowestIds[item.feedId] = item.id;
          }
        };

        Cache.prototype.buildFolderCache = function(id) {
          var feed, _i, _len, _ref, _results;
          if (this.folderCacheLastModified !== this.feedModel.getLastModified()) {
            this.folderCache = {};
            this.folderCacheLastModified = this.feedModel.getLastModified();
          }
          if (this.folderCache[id] === void 0) {
            this.folderCache[id] = [];
            _ref = this.feedModel.getItems();
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              feed = _ref[_i];
              if (feed.folderId === id) {
                _results.push(this.folderCache[id].push(feed.id));
              } else {
                _results.push(void 0);
              }
            }
            return _results;
          }
        };

        Cache.prototype.getFeedsOfFolderId = function(id) {
          this.buildFolderCache(id);
          return this.folderCache[id];
        };

        Cache.prototype.remove = function(item) {
          delete this.feedCache[item.feedId][item.id];
          return delete this.importantCache[item.id];
        };

        Cache.prototype.setImportant = function(itemId, isImportant) {
          if (isImportant) {
            return this.importantCache[itemId] = true;
          } else {
            return delete this.importantCache[itemId];
          }
        };

        Cache.prototype.getHighestId = function(type, id) {
          if (this.isFeed(type)) {
            return this.highestIds[id] || 0;
          } else {
            return this.highestId;
          }
        };

        Cache.prototype.getHighestTimestamp = function(type, id) {
          if (this.isFeed(type)) {
            return this.highestTimestamps[id] || 0;
          } else {
            return this.highestTimestamp;
          }
        };

        Cache.prototype.getLowestId = function(type, id) {
          if (this.isFeed(type)) {
            return this.lowestIds[id] || 0;
          } else {
            return this.lowestId;
          }
        };

        Cache.prototype.getLowestTimestamp = function(type, id) {
          if (this.isFeed(type)) {
            return this.lowestTimestamps[id] || 0;
          } else {
            return this.lowestTimestamp;
          }
        };

        Cache.prototype.isFeed = function(type) {
          return type === this.feedType.Feed;
        };

        return Cache;

      })();
      return new Cache(FeedType, FeedModel, FolderModel);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('Updater', ['$rootScope', '$http', function($rootScope, $http) {}]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').factory('Controller', function() {
    var Controller;
    return Controller = (function() {

      function Controller() {}

      return Controller;

    })();
  });

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').controller('ItemController', [
    'Controller', '$scope', 'ItemModel', 'ActiveFeed', 'PersistenceNews', 'FeedModel', 'StarredCount', 'GarbageRegistry', 'ShowAll', 'Loading', '$rootScope', 'FeedType', function(Controller, $scope, ItemModel, ActiveFeed, PersistenceNews, FeedModel, StarredCount, GarbageRegistry, ShowAll, Loading, $rootScope, FeedType) {
      var ItemController;
      ItemController = (function(_super) {

        __extends(ItemController, _super);

        function ItemController($scope, itemModel, activeFeed, persistence, feedModel, starredCount, garbageRegistry, showAll, loading, $rootScope, feedType) {
          var _this = this;
          this.$scope = $scope;
          this.itemModel = itemModel;
          this.activeFeed = activeFeed;
          this.persistence = persistence;
          this.feedModel = feedModel;
          this.starredCount = starredCount;
          this.garbageRegistry = garbageRegistry;
          this.showAll = showAll;
          this.loading = loading;
          this.$rootScope = $rootScope;
          this.feedType = feedType;
          this.batchSize = 4;
          this.loaderQueue = 0;
          this.$scope.getItems = function(type, id) {
            return _this.itemModel.getItemsByTypeAndId(type, id);
          };
          this.$scope.items = this.itemModel.getItems();
          this.$scope.loading = this.loading;
          this.$scope.scroll = function() {};
          this.$scope.activeFeed = this.activeFeed;
          this.$scope.$on('read', function(scope, params) {
            return _this.$scope.markRead(params.id, params.feed);
          });
          this.$scope.loadFeed = function(feedId) {
            var params;
            params = {
              id: feedId,
              type: _this.feedType.Feed
            };
            return _this.$rootScope.$broadcast('loadFeed', params);
          };
          this.$scope.markRead = function(itemId, feedId) {
            var feed, item;
            item = _this.itemModel.getItemById(itemId);
            feed = _this.feedModel.getItemById(feedId);
            if (!item.keptUnread && !item.isRead) {
              item.isRead = true;
              feed.unreadCount -= 1;
              if (!_this.showAll.showAll) {
                _this.garbageRegistry.register(item);
              }
              return _this.persistence.markRead(itemId, true);
            }
          };
          this.$scope.keepUnread = function(itemId, feedId) {
            var feed, item;
            item = _this.itemModel.getItemById(itemId);
            feed = _this.feedModel.getItemById(feedId);
            item.keptUnread = !item.keptUnread;
            if (item.isRead) {
              item.isRead = false;
              feed.unreadCount += 1;
              return _this.persistence.markRead(itemId, false);
            }
          };
          this.$scope.isKeptUnread = function(itemId) {
            return _this.itemModel.getItemById(itemId).keptUnread;
          };
          this.$scope.toggleImportant = function(itemId) {
            var item;
            item = _this.itemModel.getItemById(itemId);
            _this.itemModel.setImportant(itemId, !item.isImportant);
            if (item.isImportant) {
              _this.starredCount.count += 1;
            } else {
              _this.starredCount.count -= 1;
            }
            return _this.persistence.setImportant(itemId, item.isImportant);
          };
        }

        return ItemController;

      })(Controller);
      return new ItemController($scope, ItemModel, ActiveFeed, PersistenceNews, FeedModel, StarredCount, GarbageRegistry, ShowAll, Loading, $rootScope, FeedType);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').controller('FeedController', [
    'Controller', '$scope', 'FeedModel', 'FeedType', 'FolderModel', 'ActiveFeed', 'PersistenceNews', 'StarredCount', 'ShowAll', 'ItemModel', 'GarbageRegistry', '$rootScope', 'Loading', 'Config', function(Controller, $scope, FeedModel, FeedType, FolderModel, ActiveFeed, PersistenceNews, StarredCount, ShowAll, ItemModel, GarbageRegistry, $rootScope, Loading, Config) {
      var FeedController;
      FeedController = (function(_super) {

        __extends(FeedController, _super);

        function FeedController($scope, feedModel, folderModel, feedType, activeFeed, persistence, starredCount, showAll, itemModel, garbageRegistry, $rootScope, loading, config) {
          var _this = this;
          this.$scope = $scope;
          this.feedModel = feedModel;
          this.folderModel = folderModel;
          this.feedType = feedType;
          this.activeFeed = activeFeed;
          this.persistence = persistence;
          this.starredCount = starredCount;
          this.showAll = showAll;
          this.itemModel = itemModel;
          this.garbageRegistry = garbageRegistry;
          this.$rootScope = $rootScope;
          this.loading = loading;
          this.config = config;
          this.showSubscriptions = true;
          this.$scope.feeds = this.feedModel.getItems();
          this.$scope.folders = this.folderModel.getItems();
          this.$scope.feedType = this.feedType;
          this.$scope.toggleFolder = function(folderId) {
            var folder;
            folder = _this.folderModel.getItemById(folderId);
            folder.open = !folder.open;
            return _this.persistence.collapseFolder(folder.id, folder.open);
          };
          this.$scope.isFeedActive = function(type, id) {
            if (type === _this.activeFeed.type && id === _this.activeFeed.id) {
              return true;
            } else {
              return false;
            }
          };
          this.$scope.loadFeed = function(type, id) {
            return _this.loadFeed(type, id);
          };
          this.$scope.getUnreadCount = function(type, id) {
            var count;
            count = _this.getUnreadCount(type, id);
            if (count > 999) {
              return "999+";
            } else {
              return count;
            }
          };
          this.$scope.renameFolder = function() {
            return alert('not implemented yet, needs better solution');
          };
          this.$scope.triggerHideRead = function() {
            return _this.triggerHideRead();
          };
          this.$scope.isShown = function(type, id) {
            switch (type) {
              case _this.feedType.Subscriptions:
                return _this.showSubscriptions;
              case _this.feedType.Starred:
                return _this.starredCount.count > 0;
            }
          };
          this.$scope["delete"] = function(type, id) {
            switch (type) {
              case _this.feedType.Folder:
                _this.folderModel.removeById(id);
                return _this.persistence.deleteFolder(id);
              case _this.feedType.Feed:
                _this.feedModel.removeById(id);
                return _this.persistence.deleteFeed(id);
            }
          };
          this.$scope.markAllRead = function(type, id) {
            var feed, feedId, item, itemId, mostRecentItemId, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4, _results, _results1;
            switch (type) {
              case _this.feedType.Feed:
                _ref = _this.itemModel.getItemsByTypeAndId(type, id);
                for (itemId in _ref) {
                  item = _ref[itemId];
                  item.isRead = true;
                }
                feed = _this.feedModel.getItemById(id);
                feed.unreadCount = 0;
                mostRecentItemId = _this.itemModel.getHighestId(type, id);
                return _this.persistence.setAllItemsRead(feed.id, mostRecentItemId);
              case _this.feedType.Folder:
                _ref1 = _this.itemModel.getItemsByTypeAndId(type, id);
                for (itemId in _ref1) {
                  item = _ref1[itemId];
                  item.isRead = true;
                }
                _ref2 = _this.itemModel.getFeedsOfFolderId(id);
                _results = [];
                for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
                  feedId = _ref2[_i];
                  feed = _this.feedModel.getItemById(feedId);
                  feed.unreadCount = 0;
                  mostRecentItemId = _this.itemModel.getHighestId(type, feedId);
                  _results.push(_this.persistence.setAllItemsRead(feedId, mostRecentItemId));
                }
                return _results;
                break;
              case _this.feedType.Subscriptions:
                _ref3 = _this.itemModel.getItemsByTypeAndId(type, id);
                for (itemId in _ref3) {
                  item = _ref3[itemId];
                  item.isRead = true;
                }
                _ref4 = _this.feedModel.getItems();
                _results1 = [];
                for (_j = 0, _len1 = _ref4.length; _j < _len1; _j++) {
                  feed = _ref4[_j];
                  feed.unreadCount = 0;
                  mostRecentItemId = _this.itemModel.getHighestId(type, feed.id);
                  _results1.push(_this.persistence.setAllItemsRead(feed.id, mostRecentItemId));
                }
                return _results1;
            }
          };
          this.$scope.$on('triggerHideRead', function() {
            _this.itemModel.clearCache();
            _this.triggerHideRead();
            return _this.loadFeed(activeFeed.type, activeFeed.id);
          });
          this.$scope.$on('loadFeed', function(scope, params) {
            return _this.loadFeed(params.type, params.id);
          });
          this.$scope.$on('moveFeedToFolder', function(scope, params) {
            return _this.moveFeedToFolder(params.feedId, params.folderId);
          });
          setInterval(function() {
            return _this.updateFeeds();
          }, this.config.FeedUpdateInterval);
        }

        FeedController.prototype.updateFeeds = function() {
          var feed, _i, _len, _ref, _results;
          _ref = this.feedModel.getItems();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            feed = _ref[_i];
            _results.push(this.persistence.updateFeed(feed.id));
          }
          return _results;
        };

        FeedController.prototype.moveFeedToFolder = function(feedId, folderId) {
          var feed;
          feed = this.feedModel.getItemById(feedId);
          if (feed.folderId !== folderId) {
            feed.folderId = folderId;
            this.feedModel.markAccessed();
            return this.persistence.moveFeedToFolder(feedId, folderId);
          }
        };

        FeedController.prototype.loadFeed = function(type, id) {
          if (type !== this.activeFeed.type || id !== this.activeFeed.id) {
            if (!(type === this.feedType.Feed && this.activeFeed.type === this.feedType.Feed)) {
              this.itemModel.clearCache();
            }
          }
          this.activeFeed.id = id;
          this.activeFeed.type = type;
          this.$scope.triggerHideRead();
          return this.persistence.loadFeed(type, id, this.itemModel.getHighestId(type, id), this.itemModel.getHighestTimestamp(type, id), this.config.initialLoadedItemsNr);
        };

        FeedController.prototype.triggerHideRead = function() {
          var feed, folder, preventParentFolder, _i, _j, _len, _len1, _ref, _ref1;
          preventParentFolder = 0;
          _ref = this.feedModel.getItems();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            feed = _ref[_i];
            if (this.showAll.showAll === false && this.getUnreadCount(this.feedType.Feed, feed.id) === 0) {
              if (this.activeFeed.type === this.feedType.Feed && this.activeFeed.id === feed.id) {
                feed.show = true;
                preventParentFolder = feed.folderId;
              } else {
                feed.show = false;
              }
            } else {
              feed.show = true;
            }
          }
          _ref1 = this.folderModel.getItems();
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            folder = _ref1[_j];
            if (this.showAll.showAll === false && this.getUnreadCount(this.feedType.Folder, folder.id) === 0) {
              if ((this.activeFeed.type === this.feedType.Folder && this.activeFeed.id === folder.id) || preventParentFolder === folder.id) {
                folder.show = true;
              } else {
                folder.show = false;
              }
            } else {
              folder.show = true;
            }
          }
          if (this.showAll.showAll === false && this.getUnreadCount(this.feedType.Subscriptions, 0) === 0) {
            if (this.activeFeed.type === this.feedType.Subscriptions) {
              this.showSubscriptions = true;
            } else {
              this.showSubscriptions = false;
            }
          } else {
            this.showSubscriptions = true;
          }
          if (this.showAll.showAll === false && this.getUnreadCount(this.feedType.Starred, 0) === 0) {
            if (this.activeFeed.type === this.feedType.Starred) {
              this.showStarred = true;
            } else {
              this.showStarred = false;
            }
          } else {
            this.showStarred = true;
          }
          return this.garbageRegistry.clear();
        };

        FeedController.prototype.getUnreadCount = function(type, id) {
          var counter, feed, _i, _j, _len, _len1, _ref, _ref1;
          switch (type) {
            case this.feedType.Feed:
              return this.feedModel.getItemById(id).unreadCount;
            case this.feedType.Folder:
              counter = 0;
              _ref = this.feedModel.getItems();
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                feed = _ref[_i];
                if (feed.folderId === id) {
                  counter += feed.unreadCount;
                }
              }
              return counter;
            case this.feedType.Starred:
              return this.starredCount.count;
            case this.feedType.Subscriptions:
              counter = 0;
              _ref1 = this.feedModel.getItems();
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                feed = _ref1[_j];
                counter += feed.unreadCount;
              }
              return counter;
          }
        };

        return FeedController;

      })(Controller);
      return new FeedController($scope, FeedModel, FolderModel, FeedType, ActiveFeed, PersistenceNews, StarredCount, ShowAll, ItemModel, GarbageRegistry, $rootScope, Loading, Config);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').controller('SettingsController', [
    'Controller', '$scope', 'ShowAll', '$rootScope', 'PersistenceNews', 'FolderModel', 'FeedModel', function(Controller, $scope, ShowAll, $rootScope, PersistenceNews, FolderModel, FeedModel) {
      var SettingsController;
      SettingsController = (function(_super) {

        __extends(SettingsController, _super);

        function SettingsController($scope, $rootScope, showAll, persistence, folderModel, feedModel) {
          var _this = this;
          this.$scope = $scope;
          this.$rootScope = $rootScope;
          this.showAll = showAll;
          this.persistence = persistence;
          this.folderModel = folderModel;
          this.feedModel = feedModel;
          this.add = false;
          this.settings = false;
          this.addingFeed = false;
          this.addingFolder = false;
          this.$scope.getFolders = function() {
            return _this.folderModel.getItems();
          };
          this.$scope.getShowAll = function() {
            return _this.showAll.showAll;
          };
          this.$scope.setShowAll = function(value) {
            _this.showAll.showAll = value;
            _this.persistence.showAll(value);
            return _this.$rootScope.$broadcast('triggerHideRead');
          };
          this.$scope.toggleSettings = function() {
            if (_this.add) {
              _this.add = false;
            }
            return _this.settings = !_this.settings;
          };
          this.$scope.toggleAdd = function() {
            if (_this.settings) {
              _this.settings = false;
            }
            return _this.add = !_this.add;
          };
          this.$scope.isExpanded = function() {
            return _this.settings || _this.add;
          };
          this.$scope.addIsShown = function() {
            return _this.add;
          };
          this.$scope.settingsAreShown = function() {
            return _this.settings;
          };
          this.$scope.isAddingFeed = function() {
            return _this.addingFeed;
          };
          this.$scope.isAddingFolder = function() {
            return _this.addingFolder;
          };
          this.$scope.addFeed = function(url, folder) {
            var feed, folderId, onError, onSuccess, _i, _len, _ref;
            _this.$scope.feedEmptyError = false;
            _this.$scope.feedExistsError = false;
            _this.$scope.feedError = false;
            if (url === void 0 || url.trim() === '') {
              _this.$scope.feedEmptyError = true;
            } else {
              url = url.trim();
              _ref = _this.feedModel.getItems();
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                feed = _ref[_i];
                if (url === feed.url) {
                  _this.$scope.feedExistsError = true;
                }
              }
            }
            if (!(_this.$scope.feedEmptyError || _this.$scope.feedExistsError)) {
              if (folder === void 0) {
                folderId = 0;
              } else {
                folderId = folder.id;
              }
              _this.addingFeed = true;
              onSuccess = function() {
                _this.$scope.feedUrl = '';
                return _this.addingFeed = false;
              };
              onError = function() {
                _this.$scope.feedError = true;
                return _this.addingFeed = false;
              };
              return _this.persistence.createFeed(url, folderId, onSuccess, onError);
            }
          };
          this.$scope.addFolder = function(name) {
            var folder, onSuccess, _i, _len, _ref;
            _this.$scope.folderEmptyError = false;
            _this.$scope.folderExistsError = false;
            if (name === void 0 || name.trim() === '') {
              _this.$scope.folderEmptyError = true;
            } else {
              name = name.trim();
              _ref = _this.folderModel.getItems();
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                folder = _ref[_i];
                if (name.toLowerCase() === folder.name.toLowerCase()) {
                  _this.$scope.folderExistsError = true;
                }
              }
            }
            if (!(_this.$scope.folderEmptyError || _this.$scope.folderExistsError)) {
              _this.addingFolder = true;
              onSuccess = function() {
                _this.$scope.folderName = '';
                return _this.addingFolder = false;
              };
              return _this.persistence.createFolder(name, onSuccess);
            }
          };
          this.$scope.$on('appfocus', function() {
            _this.add = false;
            return _this.settings = false;
          });
        }

        return SettingsController;

      })(Controller);
      return new SettingsController($scope, $rootScope, ShowAll, PersistenceNews, FolderModel, FeedModel);
    }
  ]);

  /*
  # ownCloud - News app
  #
  # @author Bernhard Posselt
  # Copyright (c) 2012 - Bernhard Posselt <nukeawhale@gmail.com>
  #
  # This file is licensed under the Affero General Public License version 3 or later.
  # See the COPYING-README file
  #
  */


  angular.module('News').controller('SettingsController', [
    'Controller', '$scope', 'ShowAll', '$rootScope', 'PersistenceNews', 'FolderModel', 'FeedModel', function(Controller, $scope, ShowAll, $rootScope, PersistenceNews, FolderModel, FeedModel) {
      var SettingsController;
      SettingsController = (function(_super) {

        __extends(SettingsController, _super);

        function SettingsController($scope, $rootScope, showAll, persistence, folderModel, feedModel) {
          var _this = this;
          this.$scope = $scope;
          this.$rootScope = $rootScope;
          this.showAll = showAll;
          this.persistence = persistence;
          this.folderModel = folderModel;
          this.feedModel = feedModel;
          this.add = false;
          this.settings = false;
          this.addingFeed = false;
          this.addingFolder = false;
          this.$scope.getFolders = function() {
            return _this.folderModel.getItems();
          };
          this.$scope.getShowAll = function() {
            return _this.showAll.showAll;
          };
          this.$scope.setShowAll = function(value) {
            _this.showAll.showAll = value;
            _this.persistence.showAll(value);
            return _this.$rootScope.$broadcast('triggerHideRead');
          };
          this.$scope.toggleSettings = function() {
            if (_this.add) {
              _this.add = false;
            }
            return _this.settings = !_this.settings;
          };
          this.$scope.toggleAdd = function() {
            if (_this.settings) {
              _this.settings = false;
            }
            return _this.add = !_this.add;
          };
          this.$scope.isExpanded = function() {
            return _this.settings || _this.add;
          };
          this.$scope.addIsShown = function() {
            return _this.add;
          };
          this.$scope.settingsAreShown = function() {
            return _this.settings;
          };
          this.$scope.isAddingFeed = function() {
            return _this.addingFeed;
          };
          this.$scope.isAddingFolder = function() {
            return _this.addingFolder;
          };
          this.$scope.addFeed = function(url, folder) {
            var feed, folderId, onError, onSuccess, _i, _len, _ref;
            _this.$scope.feedEmptyError = false;
            _this.$scope.feedExistsError = false;
            _this.$scope.feedError = false;
            if (url === void 0 || url.trim() === '') {
              _this.$scope.feedEmptyError = true;
            } else {
              url = url.trim();
              _ref = _this.feedModel.getItems();
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                feed = _ref[_i];
                if (url === feed.url) {
                  _this.$scope.feedExistsError = true;
                }
              }
            }
            if (!(_this.$scope.feedEmptyError || _this.$scope.feedExistsError)) {
              if (folder === void 0) {
                folderId = 0;
              } else {
                folderId = folder.id;
              }
              _this.addingFeed = true;
              onSuccess = function() {
                _this.$scope.feedUrl = '';
                return _this.addingFeed = false;
              };
              onError = function() {
                _this.$scope.feedError = true;
                return _this.addingFeed = false;
              };
              return _this.persistence.createFeed(url, folderId, onSuccess, onError);
            }
          };
          this.$scope.addFolder = function(name) {
            var folder, onSuccess, _i, _len, _ref;
            _this.$scope.folderEmptyError = false;
            _this.$scope.folderExistsError = false;
            if (name === void 0 || name.trim() === '') {
              _this.$scope.folderEmptyError = true;
            } else {
              name = name.trim();
              _ref = _this.folderModel.getItems();
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                folder = _ref[_i];
                if (name.toLowerCase() === folder.name.toLowerCase()) {
                  _this.$scope.folderExistsError = true;
                }
              }
            }
            if (!(_this.$scope.folderEmptyError || _this.$scope.folderExistsError)) {
              _this.addingFolder = true;
              onSuccess = function() {
                _this.$scope.folderName = '';
                return _this.addingFolder = false;
              };
              return _this.persistence.createFolder(name, onSuccess);
            }
          };
          this.$scope.$on('appfocus', function() {
            _this.add = false;
            return _this.settings = false;
          });
        }

        return SettingsController;

      })(Controller);
      return new SettingsController($scope, $rootScope, ShowAll, PersistenceNews, FolderModel, FeedModel);
    }
  ]);

}).call(this);
